var fs = require('fs')

exports.run = (ctx) => {
    console.log('reading contract source...')
    const contractSrc = fs.readFileSync(ctx.sourceFile)

    compilerOutput = ctx.web3.eth.compile.solidity(contractSrc.toString())
    var jsonString = JSON.stringify(compilerOutput, null, '  ')
    fs.writeFileSync(ctx.compiledFile, jsonString)

    exports.compiledContract = compilerOutput

    ctx.compilerOutput = compilerOutput

    // y, this is a very bad hack!
    updateWebJsFile(compilerOutput)
}

function updateWebJsFile(compilerOutput) {
    var root = compilerOutput
    if(compilerOutput.Election != undefined)
        root = compilerOutput.Election
    
    var jsonString = JSON.stringify(root, null, '  ')

    var outStr = `
// !!! this is autogenerated by a setup script. Changes will be overwritten !!! 
export class Contracts {
    address = '<contractaddress-placeholder>'
    Election = ${jsonString}
}`

    fs.writeFileSync('generated/contracts.js', outStr)
}